In [1]:
import Utils
import pandas as pd
import numpy as np

In [2]:
# Test10.1
cov = pd.read_csv("../testfiles/data/test5_2.csv")
cov = cov.values

Utils.risk_parity_csd(cov)

array([0.03546374, 0.0258062 , 0.05646941, 0.26592028, 0.61634038])

In [3]:
# Test10.2
Utils.risk_parity_csd(cov,[2,2,2,2,1])

array([0.05024227, 0.03656021, 0.08039917, 0.3786077 , 0.45419066])

In [5]:
# Test10.3
cov = pd.read_csv("../testfiles/data/test5_2.csv").values
mu = pd.read_csv("../testfiles/data/test10_3_means.csv").values

weights,sharpratio = Utils.max_sharpe_ratio(mu=mu,cov=cov,rf=0.04)
weights

array([2.68658061e-08, 4.23956114e-09, 3.13563214e-08, 1.21741244e-01,
       8.78258694e-01])

In [ ]:
# Test10.4
weights,sharpratio = Utils.max_sharpe_ratio(mu=mu,cov=cov,rf=0.04,bounds=[(0.1,0.5)]*5)
weights

array([0.1, 0.1, 0.1, 0.5, 0.2])