In [1]:
import Utils
import pandas as pd
import numpy as np

In [2]:
# 5.1
cov_original = pd.read_csv("../testfiles/data/test5_1.csv")
X = Utils.simulate_multivariate_normal(0, cov_original, n_samples=100000, seed=42)
cov_simulation = Utils.calculate_cov(X)

print("Original covariance:")
print(cov_original)
print("\nSimulated covariance:")
print(cov_simulation)


Original covariance:
         x1        x2        x3        x4        x5
0  0.084979  0.087586  0.042304  0.008984  0.003876
1  0.087586  0.160485  0.058136  0.012345  0.005326
2  0.042304  0.058136  0.037440  0.005963  0.002573
3  0.008984  0.012345  0.005963  0.001688  0.000546
4  0.003876  0.005326  0.002573  0.000546  0.000314

Simulated covariance:
[[0.08507753 0.0880556  0.04251527 0.00900926 0.00388666]
 [0.0880556  0.16149404 0.05862977 0.01240569 0.00535507]
 [0.04251527 0.05862977 0.03767327 0.0059906  0.00259182]
 [0.00900926 0.01240569 0.0059906  0.00169218 0.00054818]
 [0.00388666 0.00535507 0.00259182 0.00054818 0.0003155 ]]


In [3]:
# 5.2
cov_original = pd.read_csv("../testfiles/data/test5_2.csv")
X = Utils.simulate_multivariate_normal(0, cov_original, n_samples=100000, seed=42)
cov_simulation = Utils.calculate_cov(X)

print("Original covariance:")
print(cov_original)
print("\nSimulated covariance:")
print(cov_simulation)


Original covariance:
         x1        x2        x3        x4        x5
0  0.084979  0.116781  0.042304  0.008984  0.003876
1  0.116781  0.160485  0.058136  0.012345  0.005326
2  0.042304  0.058136  0.037440  0.005963  0.002573
3  0.008984  0.012345  0.005963  0.001688  0.000546
4  0.003876  0.005326  0.002573  0.000546  0.000314

Simulated covariance:
[[0.0851635  0.11703456 0.04238639 0.00903489 0.00389092]
 [0.11703456 0.16083284 0.05824881 0.01241605 0.00534704]
 [0.04238639 0.05824881 0.03750026 0.00598459 0.00258326]
 [0.00903489 0.01241605 0.00598459 0.00169724 0.00054908]
 [0.00389092 0.00534704 0.00258326 0.00054908 0.00031558]]


In [4]:
# 5.3
cov_original = pd.read_csv("../testfiles/data/test5_3.csv")
cov_near_psd = Utils.near_psd_covariance(cov_original)
X = Utils.simulate_multivariate_normal(0, cov_near_psd, n_samples=100000, seed=42)
cov_simulation = Utils.calculate_cov(X)

print("Original covariance:")
print(cov_original)
print("\nSimulated covariance:")
print(cov_simulation)

Original covariance:
         x1        x2        x3        x4        x5
0  0.084979  0.000000  0.042304  0.008984  0.003876
1  0.000000  0.160485  0.058136  0.012345  0.005326
2  0.042304  0.058136  0.037440  0.005963  0.002573
3  0.008984  0.012345  0.005963  0.001688  0.000546
4  0.003876  0.005326  0.002573  0.000546  0.000314

Simulated covariance:
[[0.08516917 0.0088402  0.0378803  0.00807575 0.00347576]
 [0.0088402  0.16085952 0.05203732 0.01108068 0.00478703]
 [0.0378803  0.05203732 0.03740963 0.00602335 0.00259896]
 [0.00807575 0.01108068 0.00602335 0.00169729 0.00055357]
 [0.00347576 0.00478703 0.00259896 0.00055357 0.00031548]]


In [5]:
# 5.4
cov_original = pd.read_csv("../testfiles/data/test5_3.csv")
cov_higham = Utils.higham_covariance(cov_original)
X = Utils.simulate_multivariate_normal(0, cov_higham, n_samples=100000, seed=42)
cov_simulation = Utils.calculate_cov(X)

print("Original covariance:")
print(cov_original)
print("\nSimulated covariance:")
print(cov_simulation)

Original covariance:
         x1        x2        x3        x4        x5
0  0.084979  0.000000  0.042304  0.008984  0.003876
1  0.000000  0.160485  0.058136  0.012345  0.005326
2  0.042304  0.058136  0.037440  0.005963  0.002573
3  0.008984  0.012345  0.005963  0.001688  0.000546
4  0.003876  0.005326  0.002573  0.000546  0.000314

Simulated covariance:
[[0.08517333 0.01309177 0.0389312  0.00829819 0.00357258]
 [0.01309177 0.16085237 0.05348644 0.01138586 0.00491861]
 [0.0389312  0.05348644 0.03741521 0.00623975 0.00269247]
 [0.00829819 0.01138586 0.00623975 0.00169693 0.00057336]
 [0.00357258 0.00491861 0.00269247 0.00057336 0.00031549]]


In [6]:
# 5.5
cov_original = pd.read_csv("../testfiles/data/test5_2.csv")
cov_pca, k, cum = Utils.pca_covariance(cov_original, threshold=0.99)
X = Utils.simulate_multivariate_normal(0, cov_pca.values, n_samples=100000, seed=42)
cov_simulation = Utils.calculate_cov(X)

print("Original covariance:")
print(cov_original)
print("\nSimulated covariance:")
print(cov_simulation)

Original covariance:
         x1        x2        x3        x4        x5
0  0.084979  0.116781  0.042304  0.008984  0.003876
1  0.116781  0.160485  0.058136  0.012345  0.005326
2  0.042304  0.058136  0.037440  0.005963  0.002573
3  0.008984  0.012345  0.005963  0.001688  0.000546
4  0.003876  0.005326  0.002573  0.000546  0.000314

Simulated covariance:
[[0.08516466 0.11703615 0.0423887  0.00901528 0.00388666]
 [0.11703615 0.16083504 0.05825198 0.01238911 0.00534118]
 [0.0423887  0.05825198 0.03749684 0.0060325  0.00258884]
 [0.00901528 0.01238911 0.0060325  0.00109996 0.00047309]
 [0.00388666 0.00534118 0.00258884 0.00047309 0.00020349]]
